# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2016-08-29 02:57
from __future__ import unicode_literals

from django.db import migrations
import django_countries.fields


class Migration(migrations.Migration):

    dependencies = [
        ('cheeses', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cheese',
            name='country_of_orgin',
            field=django_countries.fields.CountryField(blank=True, max_length=2, null=True, verbose_name='Country of Origin'),
        ),
    ]
