# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2017-03-31 08:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CalItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uploadfile', models.FileField(upload_to='uploads/%Y/%m/%d/')),
            ],
        ),
    ]
