# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2016-10-12 06:42
from __future__ import unicode_literals

import autoslug.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('slug', autoslug.fields.AutoSlugField(always_update=True, editable=False, populate_from='name', unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Warehouse',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trans_in', models.DateField()),
                ('trans_out', models.DateField(blank=True, null=True)),
                ('in_amount', models.DecimalField(decimal_places=2, max_digits=5)),
                ('out_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=5)),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=5)),
                ('trans_in_man', models.CharField(max_length=255, verbose_name='CHOICES')),
                ('trans_out_man', models.CharField(blank=True, max_length=255, verbose_name='CHOICES')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='warehouse.Item')),
            ],
        ),
    ]
