# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2016-10-12 07:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='warehouse',
            name='trans_in_man',
            field=models.CharField(choices=[('\u4f0d\u5609\u7166', '\u4f0d\u5609\u7166'), ('\u5434\u5efa\u6d9b', '\u5434\u5efa\u6d9b')], max_length=255, verbose_name='\u7ecf\u624b\u4eba'),
        ),
        migrations.AlterField(
            model_name='warehouse',
            name='trans_out_man',
            field=models.CharField(blank=True, choices=[('\u4f0d\u5609\u7166', '\u4f0d\u5609\u7166'), ('\u5434\u5efa\u6d9b', '\u5434\u5efa\u6d9b')], max_length=255, verbose_name='\u51fa\u5e93\u4eba'),
        ),
    ]
