# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2016-10-14 08:05
from __future__ import unicode_literals

import autoslug.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse', '0004_auto_20161013_1703'),
    ]

    operations = [
        migrations.CreateModel(
            name='Trans',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trans_date', models.DateField(verbose_name='\u5165\u5e93\u65f6\u95f4')),
                ('trans_amount', models.DecimalField(decimal_places=2, max_digits=7)),
                ('trans_man', models.CharField(choices=[('\u4f0d\u5609\u7166', '\u4f0d\u5609\u7166'), ('\u5434\u5efa\u6d9b', '\u5434\u5efa\u6d9b')], max_length=255, verbose_name='\u7ecf\u624b\u4eba')),
            ],
        ),
        migrations.CreateModel(
            name='WarehouseItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('slug', autoslug.fields.AutoSlugField(always_update=True, editable=False, populate_from='name', unique=True)),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=7)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=7)),
            ],
        ),
        migrations.RemoveField(
            model_name='warehouse',
            name='item',
        ),
        migrations.DeleteModel(
            name='Item',
        ),
        migrations.DeleteModel(
            name='Warehouse',
        ),
        migrations.AddField(
            model_name='trans',
            name='item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='warehouse.WarehouseItem'),
        ),
    ]
